import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@razmisoft/react-confirm/styles.css";
import "./globals.css";

import { ThemeProvider } from "@/components/modules/theme/theme-provider";
import { Navigation } from "@/components/modules/navigation";
import { Footer } from "@/components/modules/footer";
import { ConfirmProvider } from "@razmisoft/react-confirm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen flex-col">
            <Navigation />
            <main className="flex-1">
              {" "}
              <ConfirmProvider>{children}</ConfirmProvider>
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
